### ISSUE TITLE
RFC: (Mono)repo organization

### ISSUE THREAD

**Issue by xendarboh** [31333337/trellis#12]
Goals:
- support development of interrelated project aspects (there will be many!)
- make dev+test+deploy easy out-of-box, escape circular versions/deps
- solid and clean foundation to build upon (example: work with og trellis in a way to evolve in and around it)
-  more delineation between context (easier git merge, and cleaner conventional commit context)
- go!

## Reorganization Exploration

This is a draft proposal (and Request for Comments) for how project organization could work/look.  Some details to be determined, like importing/export between modules that are currently integrated. This generally moves towards "trellis-as-a-library".

Using [go workspaces](https://go.dev/doc/tutorial/workspaces) for single repo with multi modules.

Can also use another monorepo tool, like nx, later as/if useful for broader, including non-go, developments.

### Local development

Development flow to init go workspace for local dev:

```sh
go work init
go work use -r .
```

This "just works" to use local go modules within the same repo and other projects can use the modules individually.

### Project directory structure

```
.
├── docs/
├── mods/                    # go modules
│   ├── 0kn
│   │   ├── cmd/
│   │   │   └── xtrellis     # single exe for launching 0KN elements (TODO: rename this)
│   │   ├── pkg/
│   │   │   ├── gateway
│   │   │   ├── proxy
│   │   │   ├── utils
│   │   │   └── ...
│   │   ├── README.md
│   │   ├── go.mod
│   │   └── go.sum
│   ├── proto/               # protocol buffers; buf workspace; prev `pb`
│   │   ├── buf.gen.yaml
│   │   ├── buf.work.yaml
│   │   ├── go.mod
│   │   ├── go.sum
│   │   └── ...
│   ├── trellis/             # upstream trellis with local evolution
│   │   ├── cmd/
│   │   ├── README.md
│   │   ├── go.mod
│   │   ├── go.sum
│   │   └── ...
│   └── umbrel-app/          # 0KN Umbrel App, for example
├── scripts/
│   ├── go-work-init.sh
│   ├── test-gateway-ci.sh
│   ├── test-gateway-io.sh
│   └── test-gateway-pipe.sh
├── example/                 # example other project (not go module)
│   ├── ...
│   └── package.json
├── .github/
├── docker-compose.yml
├── Dockerfile
├── Makefile
└── README.md
```

### References

- Go workspaces (monorepo)
  - [How to Create and Use a Go Monorepo (Golang, Workspaces)](https://scriptable.com/how-to-create-and-use-a-go-monorepo/)
  - [Tutorial: Getting started with multi-module workspaces - The Go Programming Language](https://go.dev/doc/tutorial/workspaces)
- Example go repos (naming and project structure conventions)
  - [opentofu/opentofu: OpenTofu lets you declaratively manage your cloud infrastructure.](https://github.com/opentofu/opentofu)
  - [traefik/mesh: Traefik Mesh - Simpler Service Mesh](https://github.com/traefik/mesh)
  - [traefik/traefik: The Cloud Native Application Proxy](https://github.com/traefik/traefik)

**Comment by gyrusdentatus** [comment]
Alternatively something like this:
```

.
├── docs/                        # Documentation
│   ├── architecture.md
│   └── api/
├── mods/                        # Go modules
│   ├── common/                  # Shared utilities and packages
│   │   ├── logging/
│   │   ├── error/
│   │   ├── go.mod
│   │   └── go.sum
│   ├── 0kn/
│   │   ├── cmd/
│   │   │   └── xtrellis
│   │   ├── internal/            # Internal packages
│   │   ├── pkg/                 # Exported packages
│   │   │   ├── gateway/
│   │   │   ├── proxy/
│   │   │   └── ...
│   │   ├── tests/               # Unit tests
│   │   ├── go.mod
│   │   └── go.sum
│   ├── proto/                   # Protocol buffers
│   │   ├── definitions/         # Proto definitions
│   │   ├── generated/           # Generated code
│   │   ├── go.mod
│   │   └── go.sum
│   └── trellis/                 # Trellis codebase
│       ├── cmd/
│       ├── internal/
│       ├── tests/
│       ├── go.mod
│       └── go.sum
├── scripts/                     # Utility scripts
│   ├── init.sh                  # Comments explaining purpose
│   └── test.sh
├── example/                     # Example projects
│   ├── ...
│   └── package.json
├── .github/                     # CI/CD workflows
│   └── workflows/
├── docker-compose.yml
├── Dockerfile
├── Makefile                     # Makefile with targets
└── README.md

```

but overall - the structure you propose makes sense from the look of it. Both work imho.

**Comment by xendarboh** [comment]
Cool. Similar enough to cover the big parts. It can evolve as we go.

> https://v1.manfred.life/golang/
> Use pkg/ for packages you want other people to use, and internal/ for the code your implementation details; most of the code should start in internal/ before being moved to pkg/, only after you are sure it can be useful for someone else and after it becomes mature enough, so it has less risk of changing.

alright, start in `internal/`

**Comment by gyrusdentatus** [comment]
Yes!!! Will run tests tmrw n prep CIs and all that when I am back online. 

Can you make the repo before you go afk please?

**Comment by xendarboh** [comment]
```
.
├── api/                       # Protocol Buffers
├── docs/                      # Documentation
├── go/                        # Go modules
│   ├── 0kn/
│   │   ├── cmd/
│   │   │   └── xtrellis       # single exe for launching 0KN elements (TODO: rename this)
│   │   ├── internal/
│   │   ├── pkg/
│   │   ├── go.mod
│   │   └── go.sum
│   └── trellis/               # Trellis
│       ├── cmd/
│       ├── README.md
│       ├── go.mod
│       ├── go.sum
│       └── ...
├── scripts/
│   ├── go-workspace-init.sh   # init go workspace
│   ├── test-gateway-ci.sh     # full gateway test, called by CI workflow
│   ├── test-gateway-io.sh     # test gateway I/O
│   └── test-gateway-pipe.sh   # test gateway pipe
├── .github/                   # CI/CD workflows
├── Makefile
├── docker-compose.yml
├── Dockerfile
└── README.md
```

That's an overview of where structure is currently landing from integrating insight, including from [this](https://v1.manfred.life/golang/), and what works.

In this PR: https://github.com/31333337/trellis/pull/13  w/ passing tests.

Developing: organized/updated docs
